/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Thread(props) {
  const { nodes, materials } = useGLTF("./thread.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.thread_spool.geometry}
        material={materials.material_0}
      />
    </group>
  );
}

useGLTF.preload("./thread.glb");
