/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Toolbox(props) {
  const { nodes, materials } = useGLTF("./toolbox.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Toolbox.geometry}
        material={materials["Vitra Toolbox Material"]}
      />
    </group>
  );
}

useGLTF.preload("./toolbox.glb");
